# Generated by Django 4.2.3 on 2023-07-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fav',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
