# Generated by Django 4.2.3 on 2023-07-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fav_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='character_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
