# Generated by Django 4.2.3 on 2023-07-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_comment_id_alter_comment_character_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fav',
            name='id',
        ),
        migrations.AlterField(
            model_name='fav',
            name='character_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
